version: '3.8'
services:
   angular:
     build:
       context: .
       dockerfile: cliangular.dockerfile
     ports:
      - "4200:4200"
     stdin_open: true
     tty: true
     volumes:
      - ./:/app
 
    



    

  
