version: '3'


services:
  dev:
    build:
      context: .
      dockerfile: Dockerfile
      target: deps
  builder:
    build:
        context: .
        dockerfile: Dockerfile
        target: build
  pro:
    build:
        context: .
        dockerfile: Dockerfile
        target: prod