version: '3'

services:
  backend:
    build: ./backend
    depends_on:
      - mongo
    env_file: 
      - ./env/api.env
    ports:
      - "8080:8080"
  mongo:
    image: mongo
    ports:
      - "27017:27017"
    volumes: 
      - data:/data/db
  front:
    build: ./frontend
    ports:
      - "4000:4000"
    stdin_open: true
    tty: true
    depends_on: 
      - backend

volumes: 
  data: